Repository istio/enhancements, pull requests merged in 2021-04, with the labels that each got.

#32 Add feature page for following feature: Helm Based Installation [Alpha]
  features/helm-installation.md
Labels: cla: yes, size/L

#33 Update codeowners
  CODEOWNERS
Labels: cla: yes, size/XS

#35 Auto mTLS status for Stable.
  features/auto_mtls.md
Labels: cla: yes, size/M

#36 Fix YAML formatting and add link
  FEATURES.md
  features.yaml
  features/feature_template.md
Labels: cla: yes, size/L

#37 Address comments regarding alpha for gateway topology features
  features.yaml
  features/configuring_gateway_network_topology.md
Labels: cla: yes, size/S

#40 Set codeowners to 1.10 RM
  CODEOWNERS
Labels: cla: yes, size/XS

#39 [release-1.10] Address comments regarding alpha for gateway topology features
  features.yaml
  features/configuring_gateway_network_topology.md
Labels: cla: yes, release-notes-none, size/S

#41 Fix CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS

#43 Add feature page for: Service Credential Distribution for VMs [Beta]
  features/vm-service-credential-distribution.md
Labels: cla: yes, size/L

#44 Add feature page for Istio Standalone Operator [Beta]
  features/standalone-operator.md
Labels: cla: yes, size/L

#49 Add feature status page for Service Credential Distribution [Stable]
  features/k8s-service-credential-distribution.md
Labels: cla: yes, size/L
