Repository istio/enhancements, pull requests merged in 2021-11, with the labels that each got.

#108 update dry-run feature yaml
  features.yaml
  features/dry_run_authorization_policy.md
Labels: cla: yes, size/S

#79 Add feature page for IPv6 support for Istio
  features.yaml
  features/ipv6-support.md
Labels: size/L, cla: yes

#34 Add feature page for following feature: Istio Authorization [Beta]
  features.yaml
  features/authorization.md
Labels: size/L, cla: yes

#56 Add feature status page for Istio Control Plane Installation
  features.yaml
  features/control-plane-installation.md
Labels: size/L, cla: yes

#57 Add feature page for protocol(HTT,HTTPS,TCP,gRPC) support in Istio
  features.yaml
  features/protocol-support.md
Labels: size/L, cla: yes

#75 Add feature page for DNS Proxying
  features.yaml
  features/dns-proxying.md
Labels: size/L, cla: yes

#109 Update link do to change in istio.io #10496
  features.yaml
Labels: size/XS, cla: yes

#110 [release-1.12] Update link do to change in istio.io #10496
  features.yaml
Labels: size/XS, cla: yes, release-notes-none
