Repository istio/enhancements, pull requests merged in 2021-05, with the labels that each got.

#29 Add feature page for following feature: Sidecar API [Beta]
  features/sidecar_api.md
Labels: cla: yes, size/L

#54 Update features.yaml
  features.yaml
Labels: cla: yes, size/XS

#66 [release-1.10] Update features.yaml
  features.yaml
Labels: cla: yes, release-notes-none, size/XS

#67 Fix broken link to external-controlplane doc
  features.yaml
  features/external_istiod.md
Labels: cla: yes, size/XS

#68 [release-1.10] Fix broken link to external-controlplane doc
  features.yaml
  features/external_istiod.md
Labels: cla: yes, release-notes-none, size/XS

#69 Fix istio.io build error
  features.yaml
Labels: cla: yes, size/XS

#70 [release-1.10] Fix istio.io build error
  features.yaml
Labels: cla: yes, release-notes-none, size/XS

#73 Update Kubernetes_MCS.md
  features/Kubernetes_MCS.md
Labels: cla: yes, size/S

#74 Adding MCS to feature list
  features.yaml
  features/kubernetes_mcs.md
Labels: cla: yes, size/XS

#71 Add features schema
  FEATURES.md
  features.yaml
  features_schema.json
Labels: cla: yes, size/L
