Repository istio/enhancements, pull requests merged in 2021-06, with the labels that each got.

#31 Add "Gateway Injection" feature
  features.yaml
  features/gateway_injection.md
Labels: cla: yes, size/L

#85 [release-1.10] Add "Gateway Injection" feature
  features.yaml
  features/gateway_injection.md
Labels: cla: yes, release-notes-none, size/L

#64 Update feature page for Istio CNI Plugin
  features/cni-plugin.md
Labels: cla: yes, size/S

#90 features_schema.json: Fix camelCase "maturity_notes" field.
  features_schema.json
Labels: cla: yes, size/XS
