Repository istio/enhancements, pull requests merged in 2021-07, with the labels that each got.

#87 Update feature page for CNI plugin.
  features/cni-plugin.md
Labels: cla: yes, size/S

#92 Update codeowners
  CODEOWNERS
Labels: cla: yes, size/XS

#78 Rename feature page for service-apis to gateway-apis
  features.yaml
  features/k8s-gateway-apis.md
Labels: cla: yes, size/XS

#91 FEATURES.md: Add missing level to "deprecation.next".
  FEATURES.md
Labels: cla: yes, size/XS

#95 Add revision tags feature
  features.yaml
  features/revision_tags.md
Labels: cla: yes, size/L

#88 Add a unique identifier to each feature
  FEATURES.md
  features.yaml
  features_schema.json
Labels: cla: yes, size/M
