Repository istio/enhancements, pull requests merged in 2021-08, with the labels that each got.

#94 CNI Beta Graduation.
  features.yaml
  features/cni-plugin.md
Labels: cla: yes, size/M

#97 Set release managers as CODEOWNERS for release-1.11
  CODEOWNERS
Labels: size/XS, cla: yes

#93 Promote external control plane feature to beta
  features.yaml
  features/external_istiod.md
Labels: cla: yes, size/S

#100 [release-1.11] Promote external control plane feature to beta
  features.yaml
  features/external_istiod.md
Labels: cla: yes, size/S, release-notes-none

#101 Update template to make supportability review optional
  features/feature_template.md
Labels: size/XS, cla: yes

#102 Promote gateway topology to beta
  features.yaml
  features/configuring_gateway_network_topology.md
Labels: cla: yes, size/S

#103 Revert "Promote gateway topology to beta"
  features.yaml
  features/configuring_gateway_network_topology.md
Labels: cla: yes, size/S
