Repository istio/enhancements, pull requests merged in 2022-01, with the labels that each got.

#111 DNS Proxying to Beta
  features.yaml
  features/dns-proxying.md
Labels: size/M, cla: yes

#112 promote authz dry-run to alpha
  features.yaml
  features/dry_run_authorization_policy.md
Labels: cla: yes, size/S

#117 establish enhancement tracking for telemetry api
  features.yaml
  features/telemetry_api.md
Labels: size/L

#118 [release-1.13] Automated branching step 4
  CODEOWNERS
Labels: size/XS, release-notes-none
