Repository istio/enhancements, pull requests merged in 2022-11, with the labels that each got.

#127 Promote gateway-api to beta
  features.yaml
  features/k8s-gateway-apis.md
Labels: size/M

#128 [release-1.16] Promote gateway-api to beta
  features.yaml
  features/k8s-gateway-apis.md
Labels: size/M, release-notes-none

#125 External authorization promotion
  features.yaml
  features/external_authorization.md
Labels: size/M, ok-to-test

#122 Promote security policies to stable
  features.yaml
  features/authorization.md
  features/jwt_authentication.md
Labels: size/L
