Repository istio/enhancements, pull requests merged in 2023-01, with the labels that each got.

#130 copy jwt claim to http headers
  features.yaml
  features/claim_to_header.md
Labels: size/L

#131 [release-1.17] Automated branching step 4
  CODEOWNERS
Labels: size/XS, release-notes-none

#132 Revision Tags : fix doc link
  features.yaml
Labels: size/XS

#133 [release-1.17] Revision Tags : fix doc link
  features.yaml
Labels: size/XS, release-notes-none

#134 Promote Helm installation to Beta
  features.yaml
  features/helm_v3_support.md
Labels: size/S

#135 [release-1.17] Promote Helm installation to Beta
  features.yaml
  features/helm_v3_support.md
Labels: size/S, release-notes-none

#136 Promote Canary Upgrade and Revision Tags to Beta
  features.yaml
  features/canary_based_revision_install.md
  features/revision_tags.md
Labels: size/L

#137 [release-1.17] Promote Canary Upgrade and Revision Tags to Beta
  features.yaml
  features/canary_based_revision_install.md
  features/revision_tags.md
Labels: size/L, release-notes-none

#138 Fix stable-revisions docs link
  features/revision_tags.md
Labels: size/XS

#139 [release-1.17] Fix stable-revisions docs link
  features/revision_tags.md
Labels: size/XS, release-notes-none
