Repository istio/enhancements, pull requests merged in 2023-04, with the labels that each got.

#147 Add APIs to feature schema
  features_schema.json
Labels: size/M

#145 promote Telemetry API to alpha
  features.yaml
  features/telemetry_api.md
Labels: size/S

#149 [release-1.18] Automated branching step 4
  CODEOWNERS
Labels: size/XS, release-notes-none
