Repository istio/enhancements, pull requests merged in 2024-04, with the labels that each got.

#174 Propose Gateway APIs as "Stable"
  features/k8s-gateway-apis.md
Labels: size/S

#176 Promote distroless to stable
  features.yaml
  features/distroless_images.md
Labels: size/S, release-notes-none

#177 [release-1.22] Automated branching step 4
  CODEOWNERS
Labels: size/XS
